### ISSUE TITLE
 Plugin.Maui.ImageCropper.Platform Type or name Platform does not exist in namespace Plugin.Maui.ImageCropper

### ISSUE THREAD

**Issue by sessiontalk** [Alex-Dobrynin/Xamarin.Controls.ImageCropper#11]
Plugin.Maui.ImageCropper.Platform Type or name Platform does not exist in namespace Plugin.Maui.ImageCropper

net8.0 android sdk 34

  protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
  {
     
      base.OnActivityResult(requestCode, resultCode, data);
      Plugin.Maui.ImageCropper.Platform.Droid.OnActivityResult(requestCode, resultCode, data);
      
  }

installed following pakages 
<PackageReference Include="Plugin.CurrentActivity" Version="2.1.0.4" />
   
   
<PackageReference Include="Plugin.Maui.ImageCropper" Version="1.1.3" />
   
   
<PackageReference Include="Xamarin.Controls.ImageCropper" Version="1.2.3.1" />

**Comment by Alex-Dobrynin** [comment]
Hello. Have you tried Smaple project from this repo? is there the same behavior?

**Comment by sessiontalk** [comment]
Ok the sample works but the docs need updating in activity onCreate should  be
Xamarin.Essentials.Platform.Init(this, savedInstanceState);
Controls.ImageCropper.Platform.Droid.Init(this);

This is what the sampl uses

**Comment by Alex-Dobrynin** [comment]
If you are using maui, please read this
![image](https://github.com/user-attachments/assets/13ff8f19-3df0-4413-87e7-b38775e2b98b)
