### ISSUE TITLE
Support for .net6

### ISSUE THREAD

**Issue by spinspin** [Alex-Dobrynin/Xamarin.Controls.ImageCropper#5]
Hi there thanks for this library its great. Any plans to upgrade the project to support .net6 ?

**Comment by Alex-Dobrynin** [comment]
it doesnt work in .net6 ios and android?

**Comment by spinspin** [comment]
It seems to be working for net6.0-android but not net6.0-ios I'm getting a null ref when image cropping which I wasn't before  on .net standard. However, I'll do some more investigating a pinpoint the exact issue. Ill report back.

**Comment by spinspin** [comment]
OK it's the  Current in ImageCropper.Current which is null on  net6.0-ios.

**Comment by spinspin** [comment]
If it helps I've upgraded the underlying iOS library you use  in this project "TOCropViewController"  here  https://github.com/spinspin/TimOliver.TOCropViewController.Xamarin
this is now working with net7.0-ios and  I'm using it successfully

**Comment by Alex-Dobrynin** [comment]
implemented support for .net 7
