### ISSUE TITLE
Problem in IOS - 'Bind_TOCropViewController.TOCropViewController'

### ISSUE THREAD

**Issue by hugotruffe79** [Alex-Dobrynin/Xamarin.Controls.ImageCropper#9]
I am using the nuget in MAUI and i have problem in iOS
 
 The error is
 
```
 Could not create an native instance of the type 'Bind_TOCropViewController.TOCropViewController': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
```

I am using Plugin.Maui.ImageCropper 1.1.3 with maui with net8

Note
The Demo of site, is ok but when i use the nuget, i have this problem

**Comment by Alex-Dobrynin** [comment]
could you create the test project and attach it here? it would help me a lot

**Comment by hugotruffe79** [comment]
Hi Alex

I could created a demo and the problem no exist.

Other framework that I am using is Prims, maybe this is the problem

Please. Do you can to remove the bug that i reported?

Sorry
